// <auto-generated />
namespace CaptivePortal.API.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class New_Changes_As_Per_BrithDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(New_Changes_As_Per_BrithDate));
        
        string IMigrationMetadata.Id
        {
            get { return "201709050604339_New_Changes_As_Per_BrithDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
